/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElSkeleton: typeof import("element-plus/es")["ElSkeleton"];
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
    Loading: typeof import("./src/components/MyLoading/loading.vue")["default"];
    MyCharts: typeof import("./src/components/GlobalComponents/myCharts.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}
