/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
	export interface GlobalComponents {
		ElBacktop: typeof import("element-plus/es")["ElBacktop"];
		ElButton: typeof import("element-plus/es")["ElButton"];
		ElCascader: typeof import("element-plus/es")["ElCascader"];
		ElCol: typeof import("element-plus/es")["ElCol"];
		ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"];
		ElDatePicker: typeof import("element-plus/es")["ElDatePicker"];
		ElEmpty: typeof import("element-plus/es")["ElEmpty"];
		ElForm: typeof import("element-plus/es")["ElForm"];
		ElFormItem: typeof import("element-plus/es")["ElFormItem"];
		ElInput: typeof import("element-plus/es")["ElInput"];
		ElLink: typeof import("element-plus/es")["ElLink"];
		ElOption: typeof import("element-plus/es")["ElOption"];
		ElPagination: typeof import("element-plus/es")["ElPagination"];
		ElPopconfirm: typeof import("element-plus/es")["ElPopconfirm"];
		ElRadio: typeof import("element-plus/es")["ElRadio"];
		ElRow: typeof import("element-plus/es")["ElRow"];
		ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
		ElSelect: typeof import("element-plus/es")["ElSelect"];
		ElSwitch: typeof import("element-plus/es")["ElSwitch"];
		ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
		ElTooltip: typeof import("element-plus/es")["ElTooltip"];
		RouterLink: typeof import("vue-router")["RouterLink"];
		RouterView: typeof import("vue-router")["RouterView"];
	}
}
