#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "💝💝温馨提醒🎉非错误💀：请您确保代码无误在提交代码奥~！"

echo "💝💝自动运行检查~ 🎉"

 # 提交前检查所有
# npm run CheckAll

# 只对提交的代码进行 eslint 检查和 prettier 格式化 和 stylelint 格式化
npx lint-staged
